# Generated by Django 5.0.3 on 2024-03-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
    ]
