# Generated by Django 5.0.3 on 2024-03-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('upload_photo', models.FileField(default='mydocs/myfile.pdf', upload_to='mydocs')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
