# Generated by Django 5.0.3 on 2024-03-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabelbuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Buku', models.IntegerField()),
                ('Kategori', models.TextField()),
                ('Nama_Buku', models.TextField()),
                ('Harga', models.IntegerField()),
                ('Stok', models.TextField()),
                ('Penerbit', models.TextField()),
                ('Penulis', models.TextField()),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='tabelpenerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Penerbit', models.IntegerField()),
                ('Nama', models.TextField()),
                ('Alamat', models.TextField()),
                ('Kota', models.IntegerField()),
                ('Telepon', models.TextField()),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
