# Generated by Django 5.0.3 on 2024-03-27 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybookstore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tabelbuku',
        ),
        migrations.DeleteModel(
            name='tabelpenerbit',
        ),
    ]
