# Generated by Django 5.0.3 on 2024-03-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.TextField()),
                ('ContactName', models.TextField()),
                ('Address', models.TextField()),
                ('City', models.TextField()),
                ('PostalCode', models.IntegerField(default=0)),
                ('Country', models.TextField()),
            ],
        ),
    ]
