# Generated by Django 5.0.3 on 2024-03-20 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoadm', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.IntegerField()),
                ('LastName', models.TextField()),
                ('FirstName', models.TextField()),
                ('BirthDate', models.DateField(default=datetime.datetime.now)),
                ('Photo', models.FileField(default='mydocs/myfile.pdf', upload_to='mydocs')),
                ('Notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDetailID', models.IntegerField()),
                ('OrderID', models.IntegerField()),
                ('ProductID', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
