# Generated by Django 5.0.3 on 2024-03-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoadm', '0005_orders_products_shippers_suppliers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Shippers',
            new_name='Shipper',
        ),
        migrations.RenameModel(
            old_name='Suppliers',
            new_name='Supplier',
        ),
    ]
