# Generated by Django 5.0.3 on 2024-03-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoadm', '0008_customer_photo_product_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
