# Generated by Django 5.0.3 on 2024-03-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoadm', '0012_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
