# Generated by Django 5.0.3 on 2024-03-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoadm', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
