# Generated by Django 5.0.3 on 2024-03-14 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bukumodel',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
