# Generated by Django 5.0.3 on 2024-03-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0003_bukumodel_author_bukumodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bukumodel',
            old_name='author',
            new_name='author_book',
        ),
        migrations.RenameField(
            model_name='bukumodel',
            old_name='date',
            new_name='date_book',
        ),
        migrations.RenameField(
            model_name='bukumodel',
            old_name='description',
            new_name='description_book',
        ),
        migrations.RenameField(
            model_name='bukumodel',
            old_name='file',
            new_name='file_book',
        ),
        migrations.RenameField(
            model_name='bukumodel',
            old_name='title',
            new_name='title_book',
        ),
    ]
